/** Stable, user-safe error codes returned by the API. */
export const ERROR_CODES = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  ENTITLEMENT_REQUIRED: 'ENTITLEMENT_REQUIRED',
  AI_UNAVAILABLE: 'AI_UNAVAILABLE',
  AI_INVALID_OUTPUT: 'AI_INVALID_OUTPUT',
  ASTROLOGY_CALCULATION_FAILED: 'ASTROLOGY_CALCULATION_FAILED',
  IMAGE_INVALID: 'IMAGE_INVALID',
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  STORAGE_UPLOAD_FAILED: 'STORAGE_UPLOAD_FAILED',
  READING_GENERATION_FAILED: 'READING_GENERATION_FAILED',
  PURCHASE_VALIDATION_FAILED: 'PURCHASE_VALIDATION_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
